### ISSUE TITLE
Ploi provider support

### ISSUE THREAD

**Issue by Cannonb4ll** [stephenlake/laravel-sanity#7]
Hey Stephen,

Very nice package! 🤟I was wondering if there is a possibility to support more server providers? Ploi.io also has webhook support after deployments for example.

Let me know! 🙂

**Comment by stephenlake** [comment]
Hi @Cannonb4ll, thanks for the comment.

This is actually one of my todo's, although rather than catering for specific services, it would be ideal if the package listened for pushes at source control level instead, perhaps a GitHub/GitLab/Bitbucket webhook event.

I'll keep you updated here, but I won't be starting with any updates within the next few weeks.

**Comment by stephenlake** [comment]
Thanks for the positive feedback :heart:

Supporting a broader audience is on the table, I'm just putting thought into the best possible way to do this first. One idea was to listen for pushes at source control level instead of Forge level so that all services are supported, another idea was to actually provide a free third party service via oauth, and/or lastly just add several providers as you requested which would definitely be the easiest, though not all runners will work if the payload doesn't contain the necessary data.

Will need to think about this a bit more.

**Comment by stephenlake** [comment]
@Cannonb4ll Take a look at [v1.2.0](https://github.com/stephenlake/laravel-sanity/releases/tag/v1.2.0) and the [minor upgrade steps](https://github.com/stephenlake/laravel-sanity/tree/master/docs#from-113-to-120).
